name: CI Web

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'
      - working-directory: apps/web
        run: npm ci
      - working-directory: apps/web
        run: npm run typecheck
      - working-directory: apps/web
        run: npm run lint
      - working-directory: apps/web
        run: npm run build
      - working-directory: apps/web
        run: npx playwright install chromium
